"""empty message

Revision ID: 092b863320fc
Revises: b577886219c1
Create Date: 2025-11-18 10:23:34.885260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '092b863320fc'
down_revision = 'b577886219c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentKey', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.alter_column('method',
               existing_type=mysql.ENUM('KAKAOPAY', 'TOSS'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('REQUESTED', 'APPROVED', 'CANCELLED', 'REFUNDED'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('REQUESTED', 'APPROVED', 'CANCELLED', 'REFUNDED'),
               existing_nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('KAKAOPAY', 'TOSS'),
               existing_nullable=False)
        batch_op.drop_column('type')
        batch_op.drop_column('paymentKey')

    # ### end Alembic commands ###
