"""empty message

Revision ID: 12502da06937
Revises: 40d27bdd6e8d
Create Date: 2025-11-11 15:47:12.486220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12502da06937'
down_revision = '40d27bdd6e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyze_result', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('analysis_uid', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['analysis_uid'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyze_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('analysis_uid')

    # ### end Alembic commands ###
