"""empty message

Revision ID: 2779ad84fd23
Revises: 6ef0a0ffedef
Create Date: 2025-11-20 15:13:59.412698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2779ad84fd23'
down_revision = '6ef0a0ffedef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('answer_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('answered_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('answered_at')
        batch_op.drop_column('answer_content')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
