"""empty message

Revision ID: 27ab3dc439b6
Revises: 7e74d8a6d995
Create Date: 2025-10-30 09:37:20.472602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27ab3dc439b6'
down_revision = '7e74d8a6d995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.alter_column('eattime',
               existing_type=mysql.JSON(),
               nullable=True)

    with op.batch_alter_table('routine_log', schema=None) as batch_op:
        batch_op.alter_column('performed_times',
               existing_type=mysql.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_log', schema=None) as batch_op:
        batch_op.alter_column('performed_times',
               existing_type=mysql.JSON(),
               nullable=False)

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.alter_column('eattime',
               existing_type=mysql.JSON(),
               nullable=False)

    # ### end Alembic commands ###
