"""Update user_meds taken

Revision ID: 2eccba931f6d
Revises: 55f308af7e45
Create Date: 2025-10-31 14:42:47.719283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2eccba931f6d'
down_revision = '55f308af7e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meds', schema=None) as batch_op:
        batch_op.alter_column('item_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('medicine', 'supplement'),
               existing_nullable=False)
        batch_op.alter_column('taken',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meds', schema=None) as batch_op:
        batch_op.alter_column('taken',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('item_type',
               existing_type=sa.Enum('medicine', 'supplement'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
