"""empty message

Revision ID: 367696d9e51b
Revises: b5d351460f06
Create Date: 2025-10-29 17:55:40.812654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '367696d9e51b'
down_revision = 'b5d351460f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('performed_times', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.alter_column('eattime',
               existing_type=mysql.TIME(),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.alter_column('eattime',
               existing_type=sa.JSON(),
               type_=mysql.TIME(),
               existing_nullable=False)

    op.drop_table('routine_log')
    # ### end Alembic commands ###
