"""empty message

Revision ID: 398f607e5f54
Revises: 092b863320fc
Create Date: 2025-11-18 11:37:19.214044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398f607e5f54'
down_revision = '092b863320fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('saved_points')

    # ### end Alembic commands ###
