"""empty message

Revision ID: 55f308af7e45
Revises: 898a41b77b69
Create Date: 2025-10-31 12:45:49.930749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f308af7e45'
down_revision = '898a41b77b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_meds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('predicted_name', sa.String(length=255), nullable=True),
    sa.Column('confirmed_name', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_meds')
    # ### end Alembic commands ###
