"""empty message

Revision ID: 5784dc0f96a1
Revises: abf478faad06
Create Date: 2025-10-31 17:43:08.831150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5784dc0f96a1'
down_revision = 'abf478faad06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###
