"""empty message

Revision ID: 7276b6dc05ff
Revises: cdf244ef5e18
Create Date: 2025-11-14 10:09:58.488864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7276b6dc05ff'
down_revision = 'cdf244ef5e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.drop_column('supps_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_total', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shipping_fee', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('used_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('final_amount', sa.Integer(), nullable=False))
        batch_op.drop_column('total_price')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zipcode', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('zipcode')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('final_amount')
        batch_op.drop_column('used_points')
        batch_op.drop_column('shipping_fee')
        batch_op.drop_column('items_total')

    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supps_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
