"""empty message

Revision ID: 7bbf7ff44ebd
Revises: 9e7959d48271
Create Date: 2025-11-06 12:09:07.925641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bbf7ff44ebd'
down_revision = '9e7959d48271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyze_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meds', sa.JSON(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('analyze_result_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('meds_ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyze_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meds_ingredients', mysql.JSON(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('analyze_result_ibfk_1'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('meds')

    # ### end Alembic commands ###
