"""empty message

Revision ID: 7e74d8a6d995
Revises: be89bb657abc
Create Date: 2025-10-29 18:09:38.397538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e74d8a6d995'
down_revision = 'be89bb657abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.alter_column('eattime',
               existing_type=mysql.TIME(),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.alter_column('eattime',
               existing_type=sa.JSON(),
               type_=mysql.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
