"""empty message

Revision ID: 849b56fae7fe
Revises: 7bbf7ff44ebd
Create Date: 2025-11-06 15:18:49.488092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849b56fae7fe'
down_revision = '7bbf7ff44ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('point', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('point')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
