"""empty message

Revision ID: 8605e763aeaa
Revises: 12502da06937
Create Date: 2025-11-12 16:11:05.026539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8605e763aeaa'
down_revision = '12502da06937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('method',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Enum('KAKAOPAY', 'TOSS', name='payment_method'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Enum('REQUESTED', 'APPROVED', 'CANCELLED', 'REFUNDED', name='payment_status'),
               existing_nullable=False)
        batch_op.alter_column('receipt_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('receipt_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('REQUESTED', 'APPROVED', 'CANCELLED', 'REFUNDED', name='payment_status'),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.Enum('KAKAOPAY', 'TOSS', name='payment_method'),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
