"""empty message

Revision ID: 86ba7007b50f
Revises: d4db58dc6465
Create Date: 2025-11-10 17:15:46.458070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ba7007b50f'
down_revision = 'd4db58dc6465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('drug_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('drug_id'), ['drug_id'], unique=True)

    # ### end Alembic commands ###
