"""empty message

Revision ID: 898a41b77b69
Revises: f87c94e6c444
Create Date: 2025-10-31 12:07:43.322069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898a41b77b69'
down_revision = 'f87c94e6c444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
