"""empty message

Revision ID: 8e42ef74c0e8
Revises: d8d0d6bc8af0
Create Date: 2025-11-24 15:39:39.885795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e42ef74c0e8'
down_revision = 'd8d0d6bc8af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyze_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))

    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_id')

    with op.batch_alter_table('analyze_result', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
