"""empty message

Revision ID: 9e7959d48271
Revises: f3c3096a3c0e
Create Date: 2025-11-04 10:48:36.784689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7959d48271'
down_revision = 'f3c3096a3c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyze_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('meds_ingredients', sa.JSON(), nullable=True),
    sa.Column('supps', sa.JSON(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('duplicates', sa.JSON(), nullable=True),
    sa.Column('interactions', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyze_result')
    # ### end Alembic commands ###
