"""empty message

Revision ID: b577886219c1
Revises: 59920733b6a3
Create Date: 2025-11-17 11:50:39.605484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b577886219c1'
down_revision = '59920733b6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_code', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['order_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_code')

    # ### end Alembic commands ###
