"""empty message

Revision ID: b5d351460f06
Revises: 66d97effcaaf
Create Date: 2025-10-29 17:49:01.359126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5d351460f06'
down_revision = '66d97effcaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.alter_column('eattime',
               existing_type=mysql.TIME(),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.alter_column('eattime',
               existing_type=sa.JSON(),
               type_=mysql.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
