"""empty message

Revision ID: cafb0f75c6d5
Revises: d48f071f8e3e
Create Date: 2025-10-30 14:34:04.690042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cafb0f75c6d5'
down_revision = 'd48f071f8e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['drug_id'])

    with op.batch_alter_table('routine_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('routine_log_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'routine', ['routine_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('routine_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('routine_log_ibfk_1'), 'routine', ['routine_id'], ['id'])

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
