"""empty message

Revision ID: cb7575c1e328
Revises: 7276b6dc05ff
Create Date: 2025-11-17 11:21:02.650344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb7575c1e328'
down_revision = '7276b6dc05ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('goods', schema=None) as batch_op:
    #     batch_op.alter_column('supps_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tel',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tel',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.alter_column('supps_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
