"""empty message

Revision ID: cdf244ef5e18
Revises: e75a223963f7
Create Date: 2025-11-13 11:41:40.480588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdf244ef5e18'
down_revision = 'e75a223963f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', name='order_status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', name='order_status'),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
