"""empty message

Revision ID: d8d0d6bc8af0
Revises: 2779ad84fd23
Create Date: 2025-11-24 09:49:16.389900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d0d6bc8af0'
down_revision = '2779ad84fd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_extra', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('address_extra')

    # ### end Alembic commands ###
