"""empty message

Revision ID: dbd4122a1780
Revises: 8e42ef74c0e8
Create Date: 2025-11-24 17:16:40.021444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbd4122a1780'
down_revision = '8e42ef74c0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', sa.String(length=200), nullable=True))
        batch_op.drop_column('detailed_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detailed_address', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('detail')

    # ### end Alembic commands ###
