"""empty message

Revision ID: e75a223963f7
Revises: 8605e763aeaa
Create Date: 2025-11-12 19:37:04.566145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75a223963f7'
down_revision = '8605e763aeaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_meds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('med_title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_meds')
    # ### end Alembic commands ###
