"""empty message

Revision ID: f3c3096a3c0e
Revises: 5784dc0f96a1
Create Date: 2025-11-03 16:58:48.206654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3c3096a3c0e'
down_revision = '5784dc0f96a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('predicted_name', sa.String(length=255), nullable=True),
    sa.Column('confirmed_name', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.Enum('medicine', 'supplement'), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_meds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_meds',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predicted_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('confirmed_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('item_type', mysql.ENUM('medicine', 'supplement'), nullable=False),
    sa.Column('taken', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_meds_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_drugs')
    # ### end Alembic commands ###
