"""empty message

Revision ID: f4971b1c7aee
Revises: 
Create Date: 2025-11-10 15:56:30.308782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4971b1c7aee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supps_products')
    op.drop_table('drug_contraindications')
    op.drop_table('supps_meds_interaction')
    op.drop_table('meds_products')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'USER', name='roleenum'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'USER', name='roleenum'),
               type_=mysql.VARCHAR(length=20),
               nullable=False)

    op.create_table('meds_products',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ITEM_SEQ', mysql.TEXT(), nullable=True),
    sa.Column('ITEM_NAME', mysql.TEXT(), nullable=True),
    sa.Column('ENTP_NAME', mysql.TEXT(), nullable=True),
    sa.Column('ETC_OTC_CODE', mysql.TEXT(), nullable=True),
    sa.Column('CHART', mysql.TEXT(), nullable=True),
    sa.Column('MATERIAL_NAME', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('EE_DOC_ID', mysql.TEXT(), nullable=True),
    sa.Column('UD_DOC_ID', mysql.TEXT(), nullable=True),
    sa.Column('NB_DOC_ID', mysql.TEXT(), nullable=True),
    sa.Column('INSERT_FILE', mysql.TEXT(), nullable=True),
    sa.Column('STORAGE_METHOD', mysql.TEXT(), nullable=True),
    sa.Column('VALID_TERM', mysql.TEXT(), nullable=True),
    sa.Column('MAKE_MATERIAL_FLAG', mysql.TEXT(), nullable=True),
    sa.Column('INDUTY_TYPE', mysql.TEXT(), nullable=True),
    sa.Column('TOTAL_CONTENT', mysql.TEXT(), nullable=True),
    sa.Column('MAIN_ITEM_INGR', mysql.TEXT(), nullable=True),
    sa.Column('INGR_NAME', mysql.TEXT(), nullable=True),
    sa.Column('ATC_CODE', mysql.TEXT(), nullable=True),
    sa.Column('ITEM_ENG_NAME', mysql.TEXT(), nullable=True),
    sa.Column('ENTP_ENG_NAME', mysql.TEXT(), nullable=True),
    sa.Column('MAIN_INGR_ENG', mysql.TEXT(), nullable=True),
    sa.Column('EE_DOC_TXT', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('UD_DOC_TXT', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('NB_DOC_TXT', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('PN_DOC_TXT', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('supps_meds_interaction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ingredient', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('caution_drug', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('drug_class', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('warning_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('drug_contraindications',
    sa.Column('성분명1', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('성분코드1', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('제품코드1', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('제품명1', mysql.TEXT(), nullable=True),
    sa.Column('업체명1', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('급여구분1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('성분명2', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('성분코드2', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('제품코드2', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('제품명2', mysql.TEXT(), nullable=True),
    sa.Column('업체명2', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('급여구분2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('공고번호', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('공고일자', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('금기사유', mysql.TEXT(), nullable=True),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('supps_products',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('BSSH_NM', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('PRDLST_NM', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('POG_DAYCNT', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('DISPOS', mysql.TEXT(), nullable=True),
    sa.Column('NTK_MTHD', mysql.TEXT(), nullable=True),
    sa.Column('PRIMARY_FNCLTY', mysql.TEXT(), nullable=True),
    sa.Column('IFTKN_ATNT_MATR_CN', mysql.TEXT(), nullable=True),
    sa.Column('RAWMTRL_NM', mysql.TEXT(), nullable=True),
    sa.Column('intake', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
