"""empty message

Revision ID: f8427f314e97
Revises: 849b56fae7fe
Create Date: 2025-11-06 16:14:44.242728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8427f314e97'
down_revision = '849b56fae7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_log', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_log', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
