"""empty message

Revision ID: f87c94e6c444
Revises: cafb0f75c6d5
Create Date: 2025-10-31 11:15:12.587932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f87c94e6c444'
down_revision = 'cafb0f75c6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_meds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('predicted_name', sa.String(length=255), nullable=True),
    sa.Column('confirmed_name', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('taken', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drug_products')
    op.drop_table('health_products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_products',
    sa.Column('BSSH_NM', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('PRDLST_NM', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('POG_DAYCNT', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('DISPOS', mysql.TEXT(), nullable=True),
    sa.Column('NTK_MTHD', mysql.TEXT(), nullable=True),
    sa.Column('PRIMARY_FNCLTY', mysql.TEXT(), nullable=True),
    sa.Column('IFTKN_ATNT_MATR_CN', mysql.TEXT(), nullable=True),
    sa.Column('RAWMTRL_NM', mysql.TEXT(), nullable=True),
    sa.Column('intake', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('drug_products',
    sa.Column('ITEM_SEQ', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('ITEM_NAME', mysql.TEXT(), nullable=True),
    sa.Column('ENTP_NAME', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('ETC_OTC_CODE', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('CHART', mysql.TEXT(), nullable=True),
    sa.Column('MATERIAL_NAME', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('EE_DOC_ID', mysql.TEXT(), nullable=True),
    sa.Column('UD_DOC_ID', mysql.TEXT(), nullable=True),
    sa.Column('NB_DOC_ID', mysql.TEXT(), nullable=True),
    sa.Column('INSERT_FILE', mysql.TEXT(), nullable=True),
    sa.Column('STORAGE_METHOD', mysql.TEXT(), nullable=True),
    sa.Column('VALID_TERM', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('MAKE_MATERIAL_FLAG', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('INDUTY_TYPE', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('TOTAL_CONTENT', mysql.TEXT(), nullable=True),
    sa.Column('MAIN_ITEM_INGR', mysql.TEXT(), nullable=True),
    sa.Column('INGR_NAME', mysql.TEXT(), nullable=True),
    sa.Column('ATC_CODE', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('ITEM_ENG_NAME', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('ENTP_ENG_NAME', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('MAIN_INGR_ENG', mysql.TEXT(), nullable=True),
    sa.Column('EE_DOC_TXT', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('UD_DOC_TXT', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('NB_DOC_TXT', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('PN_DOC_TXT', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_meds')
    # ### end Alembic commands ###
